import { Injectable, Logger, ServiceUnavailableException, NotFoundException, Inject } from "@nestjs/common";
import { and, eq, inArray } from "drizzle-orm";
import { DB, type Db } from "../db/db.module";
import { planningCenterLinks, users } from "../db/schema";
import { SettingsService } from "../settings/settings.service";

interface PcConfig {
  appId: string;
  secret: string;
  defaultServiceTypeId: string | null;
}

interface JsonApiResource {
  id: string;
  type: string;
  attributes?: Record<string, unknown>;
  relationships?: Record<string, { data?: { id: string; type: string } | { id: string; type: string }[] | null }>;
}
interface JsonApiResponse {
  data: JsonApiResource | JsonApiResource[];
  included?: JsonApiResource[];
  links?: { next?: string };
}

export interface PcPersonSummary {
  id: string;
  firstName: string | null;
  lastName: string | null;
  email: string | null;
  fullName: string;
}

export interface PcPositionAssignment {
  /** "Vocals", "Drums", "Sound" — the team position name. */
  positionName: string;
  /** Stable PC team_member id. */
  teamMemberId: string;
  pcPersonId: string | null;
  pcPersonName: string;
  /** "U" (unconfirmed) | "C" (confirmed) | "D" (declined). */
  status: string | null;
  /** Local user id if this PC person is linked, else null. */
  localUserId: string | null;
}

export interface PcPlanSummary {
  id: string;
  title: string;
  /** First plan time, ISO 8601. May be null if PC hasn't scheduled it yet. */
  sortDate: string | null;
  seriesTitle: string | null;
  serviceTypeId: string;
  serviceTypeName: string | null;
}

/**
 * Planning Center Services API client. Auth = Personal Access Token (app-id +
 * secret) sent as HTTP Basic — generated by an admin at
 * https://api.planningcenteronline.com/oauth/applications.
 *
 * The PC response shape is JSON:API; we flatten down to the small set of
 * fields the UI cares about. Settings are re-read on every request so an
 * operator can rotate the token without redeploying.
 */
@Injectable()
export class PlanningCenterService {
  private readonly logger = new Logger(PlanningCenterService.name);
  private static readonly BASE = "https://api.planningcenteronline.com";

  constructor(
    private readonly settings: SettingsService,
    @Inject(DB) private readonly db: Db,
  ) {}

  private async config(): Promise<PcConfig | null> {
    const appId = (await this.settings.get("planning_center.app_id")) as string | undefined;
    const secret = (await this.settings.get("planning_center.secret")) as string | undefined;
    const defaultServiceTypeId =
      ((await this.settings.get("planning_center.default_service_type_id")) as string | undefined) ??
      null;
    if (!appId || !secret) return null;
    return { appId, secret, defaultServiceTypeId };
  }

  private async apiGet(path: string): Promise<JsonApiResponse> {
    const cfg = await this.config();
    if (!cfg) throw new ServiceUnavailableException("Planning Center is not configured");
    const url = path.startsWith("http") ? path : `${PlanningCenterService.BASE}${path}`;
    const auth = `Basic ${Buffer.from(`${cfg.appId}:${cfg.secret}`).toString("base64")}`;
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 10_000);
    try {
      const res = await fetch(url, {
        method: "GET",
        headers: { authorization: auth, accept: "application/json" },
        signal: controller.signal,
      });
      if (res.status === 401) {
        throw new ServiceUnavailableException("Planning Center: invalid app-id/secret");
      }
      if (!res.ok) {
        throw new ServiceUnavailableException(`Planning Center ${res.status} ${res.statusText}`);
      }
      return (await res.json()) as JsonApiResponse;
    } catch (err) {
      if ((err as { name?: string }).name === "AbortError") {
        throw new ServiceUnavailableException("Planning Center timed out");
      }
      if (err instanceof ServiceUnavailableException) throw err;
      this.logger.debug(`Planning Center GET ${path} failed: ${(err as Error).message}`);
      throw new ServiceUnavailableException(
        `Planning Center unreachable: ${(err as Error).message}`,
      );
    } finally {
      clearTimeout(timer);
    }
  }

  async health(): Promise<{ configured: boolean; reachable: boolean; error: string | null }> {
    const cfg = await this.config();
    if (!cfg) return { configured: false, reachable: false, error: null };
    try {
      // /people/v2/me returns the authenticated PAT owner; cheapest reachability ping.
      await this.apiGet("/people/v2/me");
      return { configured: true, reachable: true, error: null };
    } catch (err) {
      return { configured: true, reachable: false, error: (err as Error).message };
    }
  }

  async listServiceTypes(): Promise<{ id: string; name: string }[]> {
    const body = await this.apiGet("/services/v2/service_types?per_page=100");
    const arr = Array.isArray(body.data) ? body.data : [body.data];
    return arr.map((r) => ({
      id: r.id,
      name: (r.attributes?.name as string) ?? "(unnamed)",
    }));
  }

  /**
   * List upcoming plans for a service type. PC's `?filter=future` returns
   * everything from "now" forward, ordered by sort_date asc. Defaults to the
   * configured default_service_type_id when no override is passed.
   */
  async listUpcomingPlans(opts: {
    serviceTypeId?: string;
    limit?: number;
  } = {}): Promise<PcPlanSummary[]> {
    const cfg = await this.config();
    if (!cfg) return [];
    const sid = opts.serviceTypeId ?? cfg.defaultServiceTypeId;
    if (!sid) return [];
    const limit = Math.max(1, Math.min(100, opts.limit ?? 10));
    const body = await this.apiGet(
      `/services/v2/service_types/${encodeURIComponent(sid)}/plans?filter=future&order=sort_date&per_page=${limit}`,
    );
    const arr = Array.isArray(body.data) ? body.data : [body.data];
    // Resolve service type name once (we already have the id).
    let serviceTypeName: string | null = null;
    try {
      const stBody = await this.apiGet(`/services/v2/service_types/${encodeURIComponent(sid)}`);
      const st = Array.isArray(stBody.data) ? stBody.data[0] : stBody.data;
      serviceTypeName = (st?.attributes?.name as string) ?? null;
    } catch {
      /* swallow — best effort */
    }
    return arr.map((r) => ({
      id: r.id,
      title: (r.attributes?.title as string) ?? (r.attributes?.dates as string) ?? "(untitled)",
      sortDate: (r.attributes?.sort_date as string) ?? null,
      seriesTitle: (r.attributes?.series_title as string) ?? null,
      serviceTypeId: sid,
      serviceTypeName,
    }));
  }

  /**
   * One plan with its times + team-member assignments + position resolution.
   * Team members come back grouped by their position via the related
   * `team_position` resource — we resolve those via `?include=team_position`
   * in a single round-trip.
   */
  async planDetail(serviceTypeId: string, planId: string): Promise<{
    plan: PcPlanSummary | null;
    times: { id: string; startsAt: string | null; endsAt: string | null; description: string | null }[];
    assignments: PcPositionAssignment[];
  }> {
    const planBody = await this.apiGet(
      `/services/v2/service_types/${encodeURIComponent(serviceTypeId)}/plans/${encodeURIComponent(planId)}`,
    );
    const planRow = Array.isArray(planBody.data) ? planBody.data[0] : planBody.data;
    const plan: PcPlanSummary | null = planRow
      ? {
          id: planRow.id,
          title:
            (planRow.attributes?.title as string) ??
            (planRow.attributes?.dates as string) ??
            "(untitled)",
          sortDate: (planRow.attributes?.sort_date as string) ?? null,
          seriesTitle: (planRow.attributes?.series_title as string) ?? null,
          serviceTypeId,
          serviceTypeName: null,
        }
      : null;

    const timesBody = await this.apiGet(
      `/services/v2/service_types/${encodeURIComponent(serviceTypeId)}/plans/${encodeURIComponent(planId)}/plan_times`,
    );
    const timesArr = Array.isArray(timesBody.data) ? timesBody.data : [timesBody.data];
    const times = timesArr.map((r) => ({
      id: r.id,
      startsAt: (r.attributes?.starts_at as string) ?? null,
      endsAt: (r.attributes?.ends_at as string) ?? null,
      description: (r.attributes?.description as string) ?? null,
    }));

    const tmBody = await this.apiGet(
      `/services/v2/service_types/${encodeURIComponent(serviceTypeId)}/plans/${encodeURIComponent(planId)}/team_members?include=team_position`,
    );
    const tmArr = Array.isArray(tmBody.data) ? tmBody.data : [tmBody.data];
    const positionMap = new Map<string, string>();
    for (const inc of tmBody.included ?? []) {
      if (inc.type === "TeamPosition") {
        positionMap.set(inc.id, (inc.attributes?.name as string) ?? "(position)");
      }
    }
    const pcPersonIds = tmArr
      .map((r) => {
        const rel = r.relationships?.person?.data;
        return rel && !Array.isArray(rel) ? rel.id : null;
      })
      .filter((x): x is string => !!x);
    const links = pcPersonIds.length
      ? await this.db
          .select({ userId: planningCenterLinks.userId, pcPersonId: planningCenterLinks.pcPersonId })
          .from(planningCenterLinks)
          .where(inArray(planningCenterLinks.pcPersonId, pcPersonIds))
      : [];
    const linkByPc = new Map(links.map((l) => [l.pcPersonId, l.userId]));

    const assignments: PcPositionAssignment[] = tmArr.map((r) => {
      const positionRel = r.relationships?.team_position?.data;
      const positionId =
        positionRel && !Array.isArray(positionRel) ? positionRel.id : null;
      const personRel = r.relationships?.person?.data;
      const pcPersonId =
        personRel && !Array.isArray(personRel) ? personRel.id : null;
      return {
        positionName: positionId ? (positionMap.get(positionId) ?? "(position)") : "(position)",
        teamMemberId: r.id,
        pcPersonId,
        pcPersonName: (r.attributes?.name as string) ?? "(unnamed)",
        status: (r.attributes?.status as string) ?? null,
        localUserId: pcPersonId ? (linkByPc.get(pcPersonId) ?? null) : null,
      };
    });

    return { plan, times, assignments };
  }

  /**
   * List PC people for the link UI. Page-by-page; we pull up to one page
   * (25-100) because realistic churches have < 1000 people and the link
   * picker filters client-side.
   */
  async listPeople(opts: { q?: string; limit?: number } = {}): Promise<PcPersonSummary[]> {
    const params = new URLSearchParams();
    params.set("per_page", String(Math.max(1, Math.min(100, opts.limit ?? 100))));
    if (opts.q) params.set("where[search_name_or_email]", opts.q);
    const body = await this.apiGet(`/people/v2/people?${params.toString()}`);
    const arr = Array.isArray(body.data) ? body.data : [body.data];
    return arr.map((r) => {
      const first = (r.attributes?.first_name as string) ?? null;
      const last = (r.attributes?.last_name as string) ?? null;
      const email =
        (r.attributes?.primary_email as string) ?? (r.attributes?.email as string) ?? null;
      const fullName =
        (r.attributes?.name as string) ?? [first, last].filter(Boolean).join(" ").trim();
      return { id: r.id, firstName: first, lastName: last, email, fullName };
    });
  }

  // ---- link management ----

  async listLinks() {
    return this.db
      .select({
        userId: planningCenterLinks.userId,
        userEmail: users.email,
        userName: users.name,
        pcPersonId: planningCenterLinks.pcPersonId,
        pcEmail: planningCenterLinks.pcEmail,
        pcFirstName: planningCenterLinks.pcFirstName,
        pcLastName: planningCenterLinks.pcLastName,
        updatedAt: planningCenterLinks.updatedAt,
      })
      .from(planningCenterLinks)
      .innerJoin(users, eq(users.id, planningCenterLinks.userId));
  }

  async myLink(userId: string) {
    const [row] = await this.db
      .select()
      .from(planningCenterLinks)
      .where(eq(planningCenterLinks.userId, userId))
      .limit(1);
    return row ?? null;
  }

  async link(userId: string, pcPersonId: string) {
    // Look up the PC person so we can snapshot their name/email — keeps the
    // link useful when PC is offline and lets us highlight email-mismatches
    // in the admin UI.
    let snapshot: { email: string | null; firstName: string | null; lastName: string | null } = {
      email: null,
      firstName: null,
      lastName: null,
    };
    try {
      const body = await this.apiGet(`/people/v2/people/${encodeURIComponent(pcPersonId)}`);
      const row = Array.isArray(body.data) ? body.data[0] : body.data;
      if (row) {
        snapshot = {
          email: (row.attributes?.primary_email as string) ?? null,
          firstName: (row.attributes?.first_name as string) ?? null,
          lastName: (row.attributes?.last_name as string) ?? null,
        };
      }
    } catch {
      /* unreachable — store id only, we'll fill on next refresh */
    }
    // Upsert: replace any existing link for this user, but disallow stealing
    // a PC person from another local user (unique constraint will reject).
    await this.db
      .insert(planningCenterLinks)
      .values({
        userId,
        pcPersonId,
        pcEmail: snapshot.email,
        pcFirstName: snapshot.firstName,
        pcLastName: snapshot.lastName,
      })
      .onConflictDoUpdate({
        target: planningCenterLinks.userId,
        set: {
          pcPersonId,
          pcEmail: snapshot.email,
          pcFirstName: snapshot.firstName,
          pcLastName: snapshot.lastName,
          updatedAt: new Date(),
        },
      });
    return this.myLink(userId);
  }

  async unlinkUser(userId: string) {
    const [row] = await this.db
      .delete(planningCenterLinks)
      .where(eq(planningCenterLinks.userId, userId))
      .returning();
    if (!row) throw new NotFoundException("Link not found");
    return { ok: true };
  }
}

// `and` import retained for future query expansion.
void and;
