import { pgTable, text, timestamp, uuid, boolean, index, bigint } from "drizzle-orm/pg-core";
import { users } from "./users";

/**
 * Helpdesk tickets (Phase 1.3 MVP). Owner-or-staff visibility:
 *   - role 'user' sees only the tickets they created
 *   - role 'support_engineer' + 'admin' see all
 *
 * `number` is a monotonic human-friendly id ("#41") shown in the UI; the uuid
 * remains the primary key. Assets, watchers, tags, attachments, and email
 * notifications come in later phases — keep this schema additive-only.
 */
export const tickets = pgTable(
  "tickets",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    // Cockroach: BIGINT GENERATED BY DEFAULT AS IDENTITY (monotonic per-row).
    number: bigint("number", { mode: "number" }).notNull().generatedByDefaultAsIdentity({
      name: "tickets_number_seq",
      startWith: 1,
    }),
    title: text("title").notNull(),
    description: text("description").notNull().default(""),
    status: text("status").notNull().default("open"), // open | in_progress | resolved | closed
    priority: text("priority").notNull().default("normal"), // low | normal | high | urgent
    createdByUserId: uuid("created_by_user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    assignedUserId: uuid("assigned_user_id").references(() => users.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
    // First non-creator comment / status-change time. Drives SLA "response
    // clock" — null while the ticket is awaiting first reply. Stamped by
    // TicketsService.addComment / update once a support engineer engages.
    firstResponseAt: timestamp("first_response_at"),
    resolvedAt: timestamp("resolved_at"),
    closedAt: timestamp("closed_at"),
  },
  (t) => ({
    createdByIdx: index("tickets_created_by_idx").on(t.createdByUserId),
    assignedIdx: index("tickets_assigned_idx").on(t.assignedUserId),
    statusIdx: index("tickets_status_idx").on(t.status),
    updatedIdx: index("tickets_updated_idx").on(t.updatedAt),
    numberIdx: index("tickets_number_idx").on(t.number),
    // Owner-scoped list is the hot ticket query: filter by creator then sort
    // by recency. The composite avoids the post-filter sort that the
    // single-column createdByIdx forces.
    ownerUpdatedIdx: index("tickets_owner_updated_idx").on(t.createdByUserId, t.updatedAt.desc()),
  }),
);

export const ticketComments = pgTable(
  "ticket_comments",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    ticketId: uuid("ticket_id")
      .notNull()
      .references(() => tickets.id, { onDelete: "cascade" }),
    authorUserId: uuid("author_user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    body: text("body").notNull(),
    // Internal comments are only visible to support_engineer + admin (i.e. holders of
    // tickets:read:any). Users never see them, even on their own tickets.
    isInternal: boolean("is_internal").notNull().default(false),
    // 'comment' = user-written; 'event' = system-logged change (status, tags, ...).
    kind: text("kind").notNull().default("comment"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => ({
    ticketIdx: index("ticket_comments_ticket_idx").on(t.ticketId, t.createdAt),
  }),
);
