import { KeyRound } from "lucide-react";
import { SetPasswordForm } from "./set-password-form";

/**
 * Single page that handles both flows — invite-accept and password-reset.
 * The token is in the URL; the form posts it back to consume + set password.
 * Linked-to from emails generated by /api/v1/auth/tokens/{invite,request-reset}.
 */
export default async function SetPasswordPage({
  searchParams,
}: {
  searchParams: Promise<{ token?: string }>;
}) {
  const { token } = await searchParams;
  return (
    <main className="flex min-h-screen items-center justify-center bg-slate-50 px-4 dark:bg-slate-950">
      <div className="w-full max-w-sm rounded-lg border border-slate-300 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <h1 className="flex items-center gap-2 text-xl font-semibold">
          <KeyRound className="h-5 w-5 text-brand-600" aria-hidden />
          Set your password
        </h1>
        <p className="mt-1 text-sm text-slate-600 dark:text-slate-400">
          One-time link from your invite or reset email. Pick a password you&apos;ll remember.
        </p>
        {token ? (
          <SetPasswordForm token={token} />
        ) : (
          <p className="mt-5 rounded-md border border-rose-300 bg-rose-50 px-3 py-2 text-sm text-rose-700 dark:border-rose-700 dark:bg-rose-950 dark:text-rose-300">
            Missing token. Please use the link in your email.
          </p>
        )}
      </div>
    </main>
  );
}
